name: Basic CI pipelie integeration

on:
  schedule:
    - cron: '30 20 * * *'

  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      script_type:
        type: choice
        description: Which script you want to run?
        options:
          - smoke.xml
          - regression.xml
        default: regression.xml

      browser_type:
        type: choice
        description: Which browser you want to use?
        options:
          - chrome
          - firefox
          - edge
        default: firefox

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Script
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
          mvn clean test -DsuiteXmlFile=featureSuite.xml 
          
          
          elif [ "${{ github.event_name }}" = "schedule" ]; then
          mvn clean test -DsuiteXmlFile=regression.xml
          
          else 
          mvn clean test -DsuiteXmlFile=${{inputs.script_type}} -DbrowserValue=${{inputs.browser_type}}
          fi

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/extent-testReports/extent.html
          
        
        
        
        
        
        
        

        


