name: Basic CI pipelie integeration

on:
  push:



jobs:
  test:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Maven
      uses: mvn clean install -DskipTests

    - name: Run Script
      uses: mvn clean test
