name: Too basic CI concept

on:
  push:

  workflow_dispatch:




jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Script
        run: mvn clean test


